### PR TITLE
Fixed matching by URL with filenames

### PR DESCRIPTION
**Pull request by stephanederer**

### CODE REVIEW

**Comment by stephanederer** [comment]
Hi Olli, I can' find your commit but 
`'#(((?<=.)/)|(?))([^/]+?\.[^/]+?$)|((?<=[^/])/$)#'`
works!

**Comment by vertexvaar** [comment]
Hey @stephanederer 

i haven't commited anything, just commented :wink: 

you tried
`'#(((?<=.)/)|(?))([^/]+?\.[^/]+?$)|((?<=[^/])/$)#'`
but can you try
`#(((?<=.)/)?)([^/]+?\.[^/]+?$)|((?<=[^/])/$)#`
without the optional capturing group?

**Comment by stephanederer** [comment]
@Olli

sure :see_no_evil::poop:

`#(((?<=.)/)?)([^/]+?\.[^/]+?$)|((?<=[^/])/$)#` does the job

**Comment by vertexvaar** [comment]
Merged in 0aa0bd393f69c5191f57721ac287c693be78d716

**Pull request closed without merging**
